spring:
  datasource:
    url: jdbc:postgresql://172.21.176.1:5432/postgres
    username: postgres
    password: Abc@123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # or create, create-drop, none
    show-sql: true